# feeder
feeder: st_gcn.feeder.Feeder
test_feeder_args:
  data_path: /multiverse/datasets/plizzari/Output_skeletons_without_missing_skeletons/xview/val_data_bones.npy
  label_path: /multiverse/datasets/plizzari/Output_skeletons_without_missing_skeletons/xview/val_label_filtered.pkl

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 60
  channel: 6
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  otpical_flow: False
  use_data_bn: True 

# test 
phase: test
device: 0
test_batch_size: 1


